spring.application.name=mag
spring.datasource.url=jdbc:postgresql://ep-tiny-wind-a11okr5z-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_qPC3X0QuVMDe
spring.jpa.hibernate.ddl-auto=update
